*** Variables ***
${BASE_URL_UI} =               %{SECRET_PROJECT_BASE_URL_UI}
${BASE_URL_API} =              %{SECRET_PROJECT_BASE_URL_API}
${COLLAR_SIMULATOR_URL_API} =  %{SECRET_PROJECT_COLLAR_SIMULATOR_API_URL}
${MESSAGE_HANDLER_URL_API} =   %{SECRET_PROJECT_MESSAGE_HANDLER_API_URL}
${GRAZING_URL_API} =           %{SECRET_PROJECT_GRAZING_API_URL}
${ALERT_URL_API} =             %{SECRET_PROJECT_ALERT_API_URL}

${API_SECRET_PROJECT_USER_EMAIL} =      %{SECRET_PROJECT_API_SECRET_PROJECT_USER_EMAIL}
${API_SECRET_PROJECT_USER_PASSWORD} =   %{SECRET_PROJECT_API_SECRET_PROJECT_USER_PASSWORD}
${UI_SECRET_PROJECT_USER_EMAIL} =       %{SECRET_PROJECT_UI_SECRET_PROJECT_USER_EMAIL}
${UI_SECRET_PROJECT_USER_PASSWORD} =    %{SECRET_PROJECT_UI_SECRET_PROJECT_USER_PASSWORD}
${UI_ADMIN_USER_EMAIL} =       %{SECRET_PROJECT_UI_ADMIN_USER_EMAIL}
${UI_ADMIN_USER_PASSWORD} =    %{SECRET_PROJECT_UI_ADMIN_USER_PASSWORD}
${UI_MANAGER_USER_EMAIL} =     %{SECRET_PROJECT_UI_MANAGER_USER_EMAIL}
${UI_MANAGER_USER_PASSWORD} =  %{SECRET_PROJECT_UI_MANAGER_USER_PASSWORD}
${UI_REGULAR_USER_EMAIL} =     %{SECRET_PROJECT_UI_REGULAR_USER_EMAIL}
${UI_REGULAR_USER_PASSWORD} =  %{SECRET_PROJECT_UI_REGULAR_USER_PASSWORD}

${DB_HOST} =                   %{SECRET_PROJECT_DB_HOST}
${DB_PORT} =                   %{SECRET_PROJECT_DB_PORT}
${DB_NAME} =                   %{SECRET_PROJECT_DB_NAME}
${DB_USER} =                   %{SECRET_PROJECT_DB_USER}
${DB_PASSWORD} =               %{SECRET_PROJECT_DB_PASSWORD}
